[project]
name = "pcp-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.9",
    "mne>=1.12.1",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pyriemann>=0.11",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "scipy-stubs~=1.17.1",
]
[tool.setuptools.packages.find]
where = ["."]
include = ["pcp_project*"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.12",
    "sphinx>=8",
    "sphinx-autodoc-typehints",
    "furo",
]
docs = [
    "sphinx>=8",
    "sphinx-autodoc-typehints",
    "furo",
]

[tool.coverage.run]
source = ["pcp_project"]

[tool.coverage.report]
show_missing = true
fail_under = 100
skip_covered = false
